# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 23:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('place', models.CharField(max_length=140)),
                ('date', models.DateTimeField()),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('rating', models.PositiveIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
